### PR TITLE
added GitBook App

### PR DESCRIPTION
**Pull request by aggroot**
I don t know about the images and copyright.. Feel free to add one if you think is necesary

### CODE REVIEW

**Comment by thetarnav** [comment]
The list in the readme is generated automatically from `projects.json`. but thanks, now I won't forget to add it ;)

**Comment by aggroot** [comment]
I should always read the readme first :)
Updated

**Comment by thetarnav** [comment]
I'm trying to doublecheck if it's actually using solid, but I cannot confirm that.

Here is a script that I'm usually using for that and it returns `false`: https://gist.github.com/thetarnav/1f9d1fe6c2b5a97b10def652400e20a5

Also I've found a react licenced bundle in the sources:

image

**Comment by belst** [comment]
you can also find `<style id="react-native-stylesheet"></style>` in the markup

**Comment by aggroot** [comment]
Hmm. it could be a bug of the extension I'm using then (Wappalyzer). Thanks for doublechecking. Next time I ll use the linked script myself. Didn t know about it.

**Comment by thetarnav** [comment]
no problem
The way solidjs is detected by the extension doesn't seem right:
https://github.com/wappalyzer/wappalyzer/blob/e0c0009302ec8880aa24217dd7281898a9833b40/src/technologies/s.json#L4549

**Pull request closed without merging**
